%YAML 1.2
---
spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  datasource:
    initial-size: 3
    min-idle: 3
    max-idle: 10
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
---
#properties
encryption:
#secretKey 길이는 128bit, 256bit 입니다.
#256bit 사용시 jdk 패치가 필요합니다.
#http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

#ivParameter 길이는 128bit 입니다.
#초기화 벡터(initialization vector; IV).
#vIV는 암호화 과정에서 사용되는 난수로서 암호화 과정이 완료된 후에 어떠한 두 문자열도
#동일한 암호문(cipher text, 암호화된 텍스트)을 만들어내지 않을 것을 보장한다.
#https://en.wikipedia.org/wiki/Initialization_vector

  secretKey: 1234567890123456
  ivParameter: 1234567890123456
recaptcha:
#https://developers.google.com/recaptcha

  siteKey: 6LdVZQcTAAAAAKJoY2ltpoRIO2aKN-gG2vz5SIWD
  secretKey:
  verifyingUri: https://www.google.com/recaptcha/api/siteverify
