%YAML 1.2
---
spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  datasource:
    initial-size: 3
    min-idle: 3
    max-idle: 10
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
